title = "NoTeC"
subtitle = "The Working Man's Automotive Data Collection Solution" 
author = "Nico OR"
content_path = "assets/latexTest/latexTest.md"
link = "articles/latexTest.html"
date = "2024-09-29"
