title = "Great Value Three Body Problem"
subtitle = "Using Too Many Moving Parts to Solve Too Many Moving Parts" 
author = "Nico OR"
content_path = "assets/gv3b/gv3b.md"
link = "articles/gv3b.html"
date = "2025-03-30"
