title = "Side Quest Sicarii"
subtitle = "A write up of doing front end the wrong way" 
author = "Nico OR"
content_path = "assets/sicarii/sicarii.md"
link = "articles/sicarii.html"
date = "2024-09-13"
