title = "The Nvidia File"
subtitle = "Equity and Risk Research on the Nature of the Beast" 
author = "Nico OR"
content_path = "assets/nvidia/nvidia.md"
link = "articles/nvidia.html"
date = "2026-08-10"
hidden = true
