title = "FSAEStats"
subtitle = "Scalable Analytics for the FSAE student competition" 
author = "Nico OR"
content_path = "assets/FSAEStats/FSAEStats.md"
link = "articles/FSAEStats.html"
date = "2025-05-08"
