title = "Super Computing 24"
subtitle = "High Performence Computing and Struggling to Network" 
author = "Nico OR"
content_path = "assets/sc24/sc24.md"
link = "articles/sc24.html"
date = "2024-19-11"
