title = "the t-distribution and its consequences"
subtitle = "Some of the mathematical leg work behind a fundamental statistical tool" 
author = "Nico OR"
content_path = "assets/ttesting/ttesting.md"
link = "articles/ttesting.html"
date = "2025-09-21"
